# pubspec.yaml (VERSION CORRIGÉE ET COMPLÈTE)
name: taches_a_faire_main
description: Une application de To-Do List gamifiée construite en Flutter.
version: 1.0.0+1 

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- DÉPENDANCES POUR L'INTERNATIONALISATION (i18n) ---
  flutter_localizations: 
    sdk: flutter         
  # ------------------------------------------------
  
  provider: ^6.0.5 
  uuid: ^4.4.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # --- CONFIGURATION POUR L'INTERNATIONALISATION ---
  generate: true # TRÈS IMPORTANT : Doit être sous 'flutter:'
  # --------------------------------------------------

  # assets:
  #   - images/a_dot_burr.jpeg
