# .github/workflows/main.yml

name: Flutter Web CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtenir le code source
      - uses: actions/checkout@v4

      # 2. Configurer l'environnement Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # 3. Installation des dépendances
      - name: Flutter Pub Get
        run: flutter pub get
        working-directory: Taches-a-faire-main # <-- CORRECTION 1

      # 4. Compiler le projet pour le web
      - name: Build Web
        run: flutter build web --release --base-href /Taches-a-faire/
        working-directory: Taches-a-faire-main # <-- CORRECTION 2

      # 5. Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Taches-a-faire-main/build/web # <-- CORRECTION 3 (Cible le dossier de sortie dans le sous-dossier)
          cname: your-custom-domain.com # Supprimez ou laissez cette ligne si vous n'avez pas de nom de domaine personnalisé
